spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    gateway:
      routes:
        - id: sign-in
          uri: http://localhost:8083
          predicates:
            - Path=/network-operational-support-system-api/auth
          filters:
            - RewritePath=/network-operational-support-system-api/auth, /auth/v1/sign-in

        - id: sign-up
          uri: http://localhost:8083
          predicates:
            - Path=/sign-up
          filters:
            - RewritePath=/sign-up, /auth/v1/sign-up

        - id: create-route
          uri: http://localhost:8080
          predicates:
            - Path=/ntwrk-prtnl-spprt-sstm-mddlwr/createRoute
          filters:
            - Authentication=true
            - RewritePath=/ntwrk-prtnl-spprt-sstm-mddlwr/createRoute, /v1/route/create

        - id: task-apply
          uri: http://localhost:8080
          predicates:
            - Path=/task/apply/**
          filters:
            - Authentication=true
            - RewritePath=/task/apply/(?<segment>.*), /v1/task/apply/$\{segment}

        - id: nodes
          uri: http://localhost:8089
          predicates:
            - Path=/nodes
          filters:
            - Authentication=true
            - RewritePath=/nodes, /v1/nodes

        - id: node-by-id
          uri: http://localhost:8089
          predicates:
            - Path=/node/**
          filters:
            - Authentication=true
            - RewritePath=/node/(?<segment>.*), /v1/node/$\{segment}

        - id: tasks-by-client-id
          uri: http://localhost:8089
          predicates:
            - Path=/tasks/**
          filters:
            - Authentication=true
            - RewritePath=/tasks/(?<segment>.*), /v1/tasks/$\{segment}

        - id: task-by-id
          uri: http://localhost:8089
          predicates:
            - Path=/task/**
          filters:
            - Authentication=true
            - RewritePath=/task/(?<segment>.*), /v1/task/$\{segment}

        - id: route
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/route
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/route, /v1/route
    stream:
      kafka:
        binder:
          brokers:
            - localhost:19092
            - localhost:29092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

auth-server:
  url: http://localhost:8083
  endpoint: /jwt/v1/validation
