server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: network-operational-support-system-back
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: postgres
  cloud:
    config:
      enabled: true
    stream:
      kafka:
        binder:
          brokers:
            - localhost:19092
            - localhost:29092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui

scheduler:
  interval: PT15M
  waitForConfirmedTime: PT05H
  maxExecutions: 4

controller:
  apply-task: /task/apply/{id}
  create-route: /route/create

client:
  calculate-route:
    url: http://localhost:8000
    endpoint: /api/routes/create_routes

zookeeper:
  url: localhost:22181
  sleepMsBetweenRetries: 1000
  maxRetries: 2
  waitTime: PT10M