spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: user
    password: postgres
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka-1:9092
            - kafka-2:9092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui

controller:
  task:
    get-by-client: /client/{clientId}
    get-by-id: /{id}
  route:
    get-all:
    get-by-id: /{id}
  client:
    delete: /delete
    create: /create
    update: /update
    get-all:
      endpoint:
      pageSize: 8
  dictionary:
    find-node: /node
    find-capacity: /capacity
    find-client: /client

client:
  get-adjacency-matrix:
    url: http://localhost:8000
    endpoint: /api/routes/get_adjacency_matrix
