server:
  port: 8083

spring:
  application:
    name: network-operational-support-system-auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: postgres
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
    stream:
      kafka:
        binder:
          brokers:
            - localhost:19092
            - localhost:29092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

token:
  signing:
    key: bmV0d29yay1vcGVyYXRpb25hbC1zdXBwb3J0LXN5c3RlbS1hdXRoLXRvcC1zZWNyZXQ=

controller:
  jwt:
    validation: /validation
  auth:
    sign-up: /sign-up
    sign-in: /sign-in

springdoc:
  swagger-ui:
    path: /swagger-ui