spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: user
    password: postgres
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka-1:9092
            - kafka-2:9092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui

scheduler:
  interval: PT15M
  waitForConfirmedTime: PT05H
  maxExecutions: 4

controller:
  apply-route: /route/apply/{id}
  create-route: /route/create

client:
  python:
    url: http://localhost:8000
    create-route:
      endpoint: /api/routes/create_routes
    create-maxflow-route:
      endpoint: /api/routes/create_maxflow_route

zookeeper:
  url: zookeeper:2181
  sleepMsBetweenRetries: 1000
  maxRetries: 2
  waitTime: PT10M