server:
  port: 8888
spring:
  application:
    name: network-operational-support-system-config
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/VanoPremudriy/network-operational-support-system
          search-paths:
            - /configs/network-operational-support-system-back