spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: user
    password: postgres
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka-1:9092
            - kafka-2:9092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

token:
  signing:
    key: bmV0d29yay1vcGVyYXRpb25hbC1zdXBwb3J0LXN5c3RlbS1hdXRoLXRvcC1zZWNyZXQ=

controller:
  jwt:
    validation: /validation
  auth:
    sign-up: /sign-up
    sign-in: /sign-in

springdoc:
  swagger-ui:
    path: /swagger-ui