spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: postgres
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true

token:
  signing:
    key: bmV0d29yay1vcGVyYXRpb25hbC1zdXBwb3J0LXN5c3RlbS1hdXRoLXRvcC1zZWNyZXQ=