server:
  port: 8888
spring:
  application:
    name: network-operational-support-system-config
  cloud:
    bus:
      enabled: true
    config:
      enabled: true
      server:
        git:
          cloneOnStart: true
          uri: https://github.com/VanoPremudriy/network-operational-support-system
          search-paths:
            - /back/configs/*
    stream:
      kafka:
        binder:
          brokers:
            - kafka-1:9092
            - kafka-2:9092