server:
  port: 8085

spring:
  application:
    name: network-operational-support-system-gateway
  config:
    import: optional:configserver:http://config-service:8888
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: sign-in
          uri: http://localhost:8083
          predicates:
            - Path=/network-operational-support-system-api/auth
          filters:
            - RewritePath=/network-operational-support-system-api/auth, /auth/v1/sign-in

        - id: sign-up
          uri: http://localhost:8083
          predicates:
            - Path=/sign-up
          filters:
            - RewritePath=/sign-up, /auth/v1/sign-up

        - id: create-route
          uri: http://localhost:8080
          predicates:
            - Path=/ntwrk-prtnl-spprt-sstm-mddlwr/createRoute
          filters:
            - Authentication=true
            - RewritePath=/ntwrk-prtnl-spprt-sstm-mddlwr/createRoute, /v1/route/create

        - id: route-apply
          uri: http://localhost:8080
          predicates:
            - Path=/route/apply/**
          filters:
            - Authentication=true
            - RewritePath=/route/apply/(?<segment>.*), /v1/route/apply/$\{segment}

        - id: tasks-by-client-id
          uri: http://localhost:8089
          predicates:
            - Path=/client/task/**
          filters:
            - Authentication=true
            - RewritePath=/client/task/(?<segment>.*), /v1/client/task/$\{segment}

        - id: task-by-id
          uri: http://localhost:8089
          predicates:
            - Path=/task/**
          filters:
            - Authentication=true
            - RewritePath=/task/(?<segment>.*), /v1/task/$\{segment}

        - id: route
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/route
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/route, /v1/route

        - id: client-delete
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/client/delete
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/client/delete, /v1/client/delete

        - id: client-create
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/client/create
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/client/create, /v1/client/create

        - id: client-update
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/client/update
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/client/update, /v1/client/update

        - id: client-get-all
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/client
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/client, /v1/client

        - id: dictionary-find-node
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/dictionaries/node
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/dictionaries/node, /v1/dictionary/node

        - id: dictionary-find-capacity
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/dictionaries/capacity
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/dictionaries/capacity, /v1/dictionary/capacity

        - id: dictionary-find-client
          uri: http://localhost:8089
          predicates:
            - Path=/network-operational-support-system-api/dictionaries/client
          filters:
            - Authentication=true
            - RewritePath=/network-operational-support-system-api/dictionaries/client, /v1/dictionary/client

    stream:
      kafka:
        binder:
          brokers:
            - localhost:19092
            - localhost:29092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true

auth-server:
  url: http://localhost:8083
  endpoint: /jwt/v1/validation
