server:
  port: 8083

spring:
  application:
    name: network-operational-support-system-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true